name: 从源码构建 Go

on:
  workflow_dispatch:  # 仅允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 打印平台信息
      run: |
        echo "=== 系统信息 ==="
        uname -a
        
        echo -e "\n=== CPU 信息 ==="
        lscpu | grep -E "Architecture|CPU(s)|Model name|Thread|Core|Socket"
        
        echo -e "\n=== 内存信息 ==="
        free -h
        
        echo -e "\n=== 系统架构 ==="
        arch
        
        echo -e "\n=== 操作系统版本 ==="
        cat /etc/os-release

    - name: 下载 Go 源码仓库
      uses: actions/checkout@v3
      with:
        repository: arror/golang
        path: go-source

    - name: 从源码构建 Go
      working-directory: go-source
      run: |
        cd src
        GOOS=linux GOARCH=amd64 ./make.bash
      
    - name: 配置 Go 环境变量
      run: |
        echo "GOROOT=${{ github.workspace }}/go-source" >> $GITHUB_ENV
        echo "${{ github.workspace }}/go-source/bin" >> $GITHUB_PATH

    - name: 验证 Go 安装
      run: |
        which go
        go env GOROOT
        go env GOOS GOARCH

    - name: 压缩并归档构建产物
      run: |
        cd go-source
        zip -r go-build-artifacts-linux-amd64.zip bin pkg
      
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: go-build-artifacts-linux-amd64
        path: go-source/go-build-artifacts-linux-amd64.zip
